=== SonnyRR/Fallout/src/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/PowerShell/PowerShell.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1"
  ],
  "name": "PowerShell",
  "officialUrl": "https://docs.microsoft.com/en-us/powershell/",
  "help": "PowerShell is a cross-platform task automation solution made up of a command-line shell, a scripting language, and a configuration management framework. PowerShell runs on Windows, Linux, and macOS.",
  "customExecutable": true,
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "ConsoleFile",
            "type": "string",
            "format": "-PSConsoleFile {value}",
            "help": "Loads the specified PowerShell console file. Enter the path and name of the console file. To create a console file, use the Export-Console cmdlet in PowerShell."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "-Version {value}",
            "help": "Starts the specified version of PowerShell. Valid values are 2.0 and 3.0. The version that you specify must be installed on the system. If Windows PowerShell 3.0 is installed on the computer, <c>3.0</c> is the default version. Otherwise, <c>2.0</c> is the default version. For more information, see <a href=\"https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell\">Installing PowerShell</a>."
          },
          {
            "name": "NoLogo",
            "type": "bool",
            "format": "-NoLogo",
            "help": "Hides the copyright banner at startup."
          },
          {
            "name": "NoExit",
            "type": "bool",
            "format": "-NoExit",
            "help": "Does not exit after running startup commands."
          },
          {
            "name": "StartUsingASingleThreadedApartment",
            "type": "bool",
            "format": "-Sta",
            "help": "Starts PowerShell using a single-threaded apartment. In Windows PowerShell 2.0, multi-threaded apartment (MTA) is the default. In Windows PowerShell 3.0, single-threaded apartment (STA) is the default."
          },
          {
            "name": "StartUsingAMultiThreadedApartment",
            "type": "bool",
            "format": "-Mta",
            "help": "Starts PowerShell using a multi-threaded apartment. This parameter is introduced in PowerShell 3.0. In PowerShell 2.0, multi-threaded apartment (MTA) is the default. In PowerShell 3.0, single-threaded apartment (STA) is the default."
          },
          {
            "name": "NoProfile",
            "type": "bool",
            "format": "-NoProfile",
            "help": "Does not load the PowerShell profile."
          },
          {
            "name": "NonInteractive",
            "type": "bool",
            "format": "-NonInteractive",
            "help": "Does not present an interactive prompt to the user."
          },
          {
            "name": "InputFormat",
            "type": "PowerShellFormat",
            "format": "-InputFormat {value}",
            "help": "Describes the format of data sent to PowerShell. Valid values are <c>Text</c> (text strings) or <c>XML</c> (serialized CLIXML format)."
          },
          {
            "name": "OutputFormat",
            "type": "PowerShellFormat",
            "format": "-OutputFormat {value}",
            "help": "Determines how output from PowerShell is formatted. Valid values are <c>Text</c>  (text strings) or <c>XML</c>  (serialized CLIXML format)."
          },
          {
            "name": "WindowStyle",
            "type": "PowerShellWindowStyle",
            "format": "-WindowStyle {value}",
            "help": "Sets the window style for the session. Valid values are <c>Normal</c>, <c>Minimized</c>, <c>Maximized</c> and <c>Hidden</c>."
          },
          {
            "name": "EncodedCommand",
            "type": "string",
            "format": "-EncodedCommand {value}",
            "help": "Accepts a base-64-encoded string version of a command. Use this parameter to submit commands to PowerShell that require complex quotation marks or curly braces. The string must be formatted using UTF-16LE character encoding."
          },
          {
            "name": "ConfigurationName",
            "type": "string",
            "format": "-ConfigurationName {value}",
            "help": "Specifies a configuration endpoint in which PowerShell is run. This can be any endpoint registered on the local machine including the default PowerShell remoting endpoints or a custom endpoint having specific user role capabilities."
          },
          {
            "name": "ExecutionPolicy",
            "type": "string",
            "format": "-ExecutionPolicy {value}",
            "help": "Sets the default execution policy for the current session and saves it in the <c>$env:PSExecutionPolicyPreference</c> environment variable. This parameter does not change the PowerShell execution policy that is set in the registry. For information about PowerShell execution policies, including a list of valid values, see <a href=\"https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies\">about_Execution_Policies</a>."
          },
          {
            "name": "File",
            "type": "string",
            "format": "-File  {value}",
            "help": "If the value of File is <c>-</c>, the command text is read from standard input. Running <c>powershell -File -</c> without redirected standard input starts a regular session. This is the same as not specifying the <c>File</c> parameter at all.<para/>If the value of File is a file path, the script runs in the local scope (<c>dot-sourced</c>), so that the functions and variables that the script creates are available in the current session. Enter the script file path and any parameters. <c>File</c> must be the last parameter in the command. All values typed after the <c>File</c> parameter are interpreted as the script file path and parameters passed to that script. Parameters passed to the script are passed as literal strings, after interpretation by the current shell. For example, if you are in cmd.exe and want to pass an environment variable value, you would use the cmd.exe syntax: <c>powershell.exe -File .\\test.ps1 -TestParam %windir%</c>.<para/>In contrast, running <c>powershell.exe -File .\\test.ps1 -TestParam $env:windir</c> in cmd.exe results in the script receiving the literal string <c>$env:windir</c> because it has no special meaning to the current cmd.exe shell. The <c>$env:windir</c> style of environment variable reference can be used inside a Command parameter, since there it will be interpreted as PowerShell code.<para/>Similarly, if you want to execute the same command from a Batch script, you would use <c>%~dp0</c> instead of <c>.\\</c> or <c>$PSScriptRoot</c> to represent the current execution directory: <c>powershell.exe -File %~dp0test.ps1 -TestParam %windir%</c>. If you instead used <c>.\\test.ps1</c>, PowerShell would throw an error because it cannot find the literal path <c>.\\test.ps1</c>.<para/>When the value of <c>File</c> is a file path, <c>File</c> must be the last parameter in the command because any characters typed after the <c>File</c> parameter name are interpreted as the script file path followed by the script parameters.<para/>You can include the script parameters and values in the value of the <c>File</c> parameter. For example: <c>-File .\\Get-Script.ps1 -Domain Central</c>.<para/>Typically, the switch parameters of a script are either included or omitted. For example, the following command uses the <c>All</c> parameter of the <c>Get-Script.ps1</c> script file: <c>-File .\\Get-Script.ps1 -All</c>.<para/>In rare cases, you might need to provide a Boolean value for a parameter. It is not possible to pass an explicit boolean value for a switch parameter when running a script in this way. This limitation was removed in PowerShell 6 (<c>pwsh.exe</c>)."
          },
          {
            "name": "FileArguments",
            "type": "List<string>",
            "format": "{value}",
            "help": "Arguments passed in when using the <c>-File</c> option."
          },
          {
            "name": "FileKeyValueParameters",
            "type": "Dictionary<string, string>",
            "format": "-{key} {value}",
            "secret": false,
            "help": "Key-value pairs passed in when using the <c>-File</c> option."
          },
          {
            "name": "Command",
            "type": "string",
            "format": "-Command {value}",
            "help": "Executes the specified commands (and any parameters) as though they were typed at the PowerShell command prompt, and then exits, unless the <c>NoExit</c> parameter is specified.<para/>The value of Command can be <c>-</c>, a script block, or a string. If the value of <c>Command</c> is <c>-</c>, the command text is read from standard input.<para/>The <c>Command</c> parameter only accepts a script block for execution when it can recognize the value passed to <c>Command</c> as a <c>ScriptBlock</c> type. This is only possible when running <c>powershell.exe</c> from another PowerShell host. The <c>ScriptBlock</c> type may be contained in an existing variable, returned from an expression, or parsed by the PowerShell host as a literal script block enclosed in curly braces (<c>{}</c>), before being passed to <c>powershell.exe</c>."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "PowerShellFormat",
      "values": [
        "Text",
        "Xml"
      ]
    },
    {
      "name": "PowerShellWindowStyle",
      "values": [
        "Normal",
        "Minimized",
        "Maximized",
        "Hidden"
      ]
    }
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/ILRepack/ILRepack.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "name": "ILRepack",
  "officialUrl": "https://github.com/gluck/il-repack#readme",
  "help": "ILRepack is meant at replacing <a href=\"https://github.com/dotnet/ILMerge\">ILMerge</a> / <a href=\"https://evain.net/blog/articles/2006/11/06/an-introduction-to-mono-merge\">Mono.Merge</a>.<para/>The former being closed-source (<a href=\"https://github.com/Microsoft/ILMerge\">now open-sourced</a>), impossible to customize, slow, resource consuming and many more. The later being deprecated, unsupported, and based on an old version of Mono.Cecil.<para/>Here we're using latest (slightly modified) Cecil sources (0.9), you can find the fork <a href=\"https://github.com/gluck/cecil\">here</a>. Mono.Posix is also required (build only, it gets merged afterwards) for executable bit set on target file.",
  "nugetPackageId": "ILRepack",
  "packageExecutable": "ILRepack.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "KeyFile",
            "type": "string",
            "format": "--keyfile:{value}",
            "secret": false,
            "help": "Specifies a keyfile to sign the output assembly."
          },
          {
            "name": "KeyContainer",
            "type": "string",
            "format": "--keycontainer:{value}",
            "secret": false,
            "help": "Specifies a key container to sign the output assembly (takes precedence over <c>--keyfile</c>)."
          },
          {
            "name": "LogFile",
            "type": "string",
            "format": "--log:{value}",
            "help": "Enable logging (to a file, if given) (default is disabled)."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--ver:{value}",
            "help": "Target assembly version."
          },
          {
            "name": "Union",
            "type": "bool",
            "format": "--union",
            "help": "Merges types with identical names into one."
          },
          {
            "name": "NoDebug",
            "type": "bool",
            "format": "--ndebug",
            "help": "Disables symbol file generation."
          },
          {
            "name": "CopyAttributes",
            "type": "bool",
            "format": "--copyattrs",
            "help": "Copy assembly attributes (by default only the primary assembly attributes are copied)."
          },
          {
            "name": "Attr",
            "type": "string",
            "format": "--attr:{value}",
            "help": "Take assembly attributes from the given assembly file."
          },
          {
            "name": "AllowMultiple",
            "type": "bool",
            "format": "--allowMultiple",
            "help": "When <c>--copyattrs</c> is specified, allows multiple attributes (if type allows)."
          },
          {
            "name": "Target",
            "type": "ILRepackTarget",
            "format": "--target:{value}",
            "help": "Specify target assembly kind (<c>library</c>, <c>exe</c>, <c>winexe</c> supported, default is same as first assembly)."
          },
          {
            "name": "TargetPlatform",
            "type": "string",
            "format": "--targetplatform:{value}",
            "help": "Specify target platform (v1, v1.1, v2, v4 supported)."
          },
          {
            "name": "Xmldocs",
            "type": "bool",
            "format": "--xmldocs",
            "help": "Merges XML documentation as well."
          },
          {
            "name": "Lib",
            "type": "string",
            "format": "--lib:{value}",
            "help": "Adds the path to the search directories for referenced assemblies (can be specified multiple times)."
          },
          {
            "name": "Internalize",
            "type": "bool",
            "format": "--internalize",
            "help": "Sets all types but the ones from the first assembly <c>internal</c>."
          },
          {
            "name": "InternalizeExcludeFile",
            "type": "string",
            "format": "--internalize:{value}",
            "help": "Exclude file contains one regex per line to compare against fullname of types NOT to internalize."
          },
          {
            "name": "RenameInternalized",
            "type": "bool",
            "format": "--renameInternalized",
            "help": "Rename all internalized types."
          },
          {
            "name": "DelaySign",
            "type": "bool",
            "format": "--delaysign",
            "help": "Sets the key, but don't sign the assembly."
          },
          {
            "name": "AllowDuplicate",
            "type": "List<string>",
            "format": "--allowdup:{value}",
            "help": "Allows the specified type for being duplicated in input assemblies."
          },
          {
            "name": "AllowDuplicateResources",
            "type": "bool",
            "format": "--allowduplicateresources",
            "help": "Allows to duplicate resources in output assembly (by default they're ignored)."
          },
          {
            "name": "ZeroPekind",
            "type": "bool",
            "format": "--zeropekind",
            "help": "Allows assemblies with Zero <c>PeKind</c> (but obviously only IL will get merged)."
          },
          {
            "name": "Wildcards",
            "type": "bool",
            "format": "--wildcards",
            "help": "Allows (and resolves) file wildcards (e.g. <c>*.dll</c>) in input assemblies."
          },
          {
            "name": "Parallel",
            "type": "bool",
            "format": "--parallel",
            "help": "Use as many CPUs as possible to merge the assemblies."
          },
          {
            "name": "Pause",
            "type": "bool",
            "format": "--pause",
            "help": "Pause execution once completed (good for debugging)."
          },
          {
            "name": "RepackDrop",
            "type": "bool",
            "format": "--repackdrop:AttributeClass",
            "help": "Allows dropping specific members during merging (<a href=\"https://github.com/gluck/il-repack/issues/215\">#215</a>)."
          },
          {
            "name": "Verbose",
            "type": "bool",
            "format": "--verbose",
            "help": "Shows more logs."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--out:{value}",
            "help": "Target assembly path, <c>symbol/config/doc</c> files will be written here as well."
          },
          {
            "name": "Assemblies",
            "type": "List<string>",
            "format": "{value}",
            "position": -1,
            "help": "Primary and other assemblies to be merged."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "ILRepackTarget",
      "values": [
        "library",
        "exe",
        "winexe"
      ]
    }
  ]
}
