=== SonnyRR/Fallout/src/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/Squirrel/Squirrel.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs"
  ],
  "name": "Squirrel",
  "officialUrl": "https://github.com/Squirrel/Squirrel.Windows",
  "help": "Squirrel is both a set of tools and a library, to completely manage both installation and updating your Desktop Windows application, written in either C# or any other language (i.e., Squirrel can manage native C++ applications).",
  "nugetPackageId": "Squirrel.Windows",
  "packageExecutable": "Squirrel.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Install",
            "type": "string",
            "format": "--install={value}",
            "help": "Install the app whose package is in the specified directory."
          },
          {
            "name": "Uninstall",
            "type": "bool",
            "format": "--uninstall",
            "help": "Uninstall the app the same dir as Update.exe."
          },
          {
            "name": "Download",
            "type": "bool",
            "format": "--download",
            "help": "Download the releases specified by the URL and write new results to stdout as JSON."
          },
          {
            "name": "CheckForUpdate",
            "type": "bool",
            "format": "--checkForUpdate",
            "help": "Check for one available update and writes new results to stdout as JSON."
          },
          {
            "name": "Update",
            "type": "string",
            "format": "--update={value}",
            "help": "Update the application to the latest remote version specified by URL."
          },
          {
            "name": "Releasify",
            "type": "string",
            "format": "--releasify={value}",
            "help": "Update or generate a releases directory with a given NuGet package."
          },
          {
            "name": "CreateShortcut",
            "type": "string",
            "format": "--createShortcut={value}",
            "help": "Create a shortcut for the given executable name."
          },
          {
            "name": "RemoveShortcut",
            "type": "string",
            "format": "--removeShortcut={value}",
            "help": "Remove a shortcut for the given executable name."
          },
          {
            "name": "UpdateSelf",
            "type": "string",
            "format": "--updateSelf={value}",
            "help": "Copy the currently executing Update.exe into the default location."
          },
          {
            "name": "ProcessStart",
            "type": "string",
            "format": "--processStart={value}",
            "help": "Start an executable in the latest version of the app package."
          },
          {
            "name": "ProcessStartAndWait",
            "type": "string",
            "format": "--processStartAndWait={value}",
            "help": "Start an executable in the latest version of the app package."
          },
          {
            "name": "ReleaseDirectory",
            "type": "string",
            "format": "--releaseDir={value}",
            "help": "Path to a release directory to use with releasify."
          },
          {
            "name": "PackagesDirectory",
            "type": "string",
            "format": "--packagesDir={value}",
            "help": "Path to the NuGet Packages directory for C# apps."
          },
          {
            "name": "BootstrapperExecutable",
            "type": "string",
            "format": "--bootstrapperExe={value}",
            "help": "Path to the Setup.exe to use as a template."
          },
          {
            "name": "LoadingGif",
            "type": "string",
            "format": "--loadingGif={value}",
            "help": "Path to an animated GIF to be displayed during installation."
          },
          {
            "name": "Icon",
            "type": "string",
            "format": "--icon={value}",
            "help": "Path to an ICO file that will be used for icon shortcuts."
          },
          {
            "name": "SetupIcon",
            "type": "string",
            "format": "--setupIcon={value}",
            "help": "Path to an ICO file that will be used for the Setup executable's icon."
          },
          {
            "name": "SignWithParameters",
            "type": "string",
            "format": "--signWithParams={value}",
            "help": "Sign the installer via SignTool.exe with the parameters given."
          },
          {
            "name": "BaseUrl",
            "type": "string",
            "format": "--baseUrl={value}",
            "help": "Provides a base URL to prefix the RELEASES file packages with."
          },
          {
            "name": "ProcessStartArguments",
            "type": "string",
            "format": "--process-start-args={value}",
            "help": "Arguments that will be used when starting executable."
          },
          {
            "name": "ShortcutLocations",
            "type": "List<string>",
            "format": "--shortcut-locations={value}",
            "separator": ",",
            "help": "Comma-separated string of shortcut locations, e.g. 'Desktop,StartMenu'."
          },
          {
            "name": "GenerateNoMsi",
            "type": "bool",
            "format": "--no-msi",
            "help": "Don't generate an MSI package."
          },
          {
            "name": "GenerateNoDelta",
            "type": "bool",
            "format": "--no-delta",
            "help": "Don't generate delta packages to save time"
          },
          {
            "name": "FrameworkVersion",
            "type": "string",
            "format": "--framework-version={value}",
            "help": "Set the required .NET framework version, e.g. net461"
          }
        ]
      }
    }
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/InnoSetup/InnoSetup.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline"
  ],
  "name": "InnoSetup",
  "officialUrl": "http://www.jrsoftware.org/isinfo.php",
  "help": "Inno Setup is a free installer for Windows programs by Jordan Russell and Martijn Laan. First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability.",
  "pathExecutable": "iscc",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "ScriptFile",
            "type": "string",
            "format": "{value}",
            "position": 1,
            "help": "The .iss script file to compile"
          },
          {
            "name": "Output",
            "type": "bool",
            "format": "/O{value}",
            "customValue": true,
            "help": "Enable or disable output (overrides <c>Output</c>)"
          },
          {
            "name": "OutputDir",
            "type": "string",
            "format": "/O{value}",
            "help": "Output files to specified path (overrides <c>OutputDir</c>)"
          },
          {
            "name": "OutputBaseFilename",
            "type": "string",
            "format": "/F{value}",
            "help": "Overrides OutputBaseFilename with the specified filename"
          },
          {
            "name": "SignTools",
            "type": "Dictionary<string, string>",
            "format": "/S{key}={value}",
            "help": "Sets a SignTool with the specified name and command"
          },
          {
            "name": "Quiet",
            "type": "bool",
            "format": "/Q",
            "help": "Quiet compile (print error messages only)"
          },
          {
            "name": "QuietWithProgress",
            "type": "bool",
            "format": "/Qp",
            "help": "Enable quiet compile while still displaying progress"
          },
          {
            "name": "KeyValueDefinitions",
            "type": "Dictionary<string, string>",
            "format": "/D{key}={value}",
            "secret": false,
            "help": "Emulate <c>#define public {name} {value}</c>"
          },
          {
            "name": "KeyDefinitions",
            "type": "List<string>",
            "format": "/D{value}",
            "secret": false,
            "help": "Emulate <c>#define public {name}</c>"
          },
          {
            "name": "Verbosity",
            "type": "int",
            "format": "/V{value}",
            "help": "Emulate <c>#pragma verboselevel {number}</c> (highest level is 9)"
          }
        ]
      }
    }
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/Discord/Discord.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://discord.com/developers/docs/resources/channel#create-message"
  ],
  "name": "Discord",
  "officialUrl": "https://discord.com/developers/docs/intro",
  "dataClasses": [
    {
      "name": "DiscordMessage",
      "extensionMethods": true,
      "properties": [
        {
          "name": "ChannelId",
          "type": "string",
          "json": "channel_id",
          "help": "Id of the channel."
        },
        {
          "name": "Content",
          "type": "string",
          "json": "content",
          "help": "Message contents (up to 2000 characters)."
        },
        {
          "name": "Nonce",
          "type": "string",
          "json": "nonce",
          "help": "Can be used to verify a message was sent (up to 25 characters). Value will appear in the <a href=\"https://discord.com/developers/docs/topics/gateway-events#message-create\">Message Create event</a>."
        },
        {
          "name": "TTS",
          "type": "bool",
          "json": "tts",
          "help": "Whether this is a TTS message."
        },
        {
          "name": "Embeds",
          "type": "List<DiscordEmbed>",
          "json": "embeds",
          "help": "Embedded rich content (up to 6000 characters). See <a href=\"https://autocode.com/tools/discord/embed-builder/\">Discord Embed Builder</a>."
        }
      ]
    },
    {
      "name": "DiscordEmbed",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Title",
          "type": "string",
          "json": "title",
          "help": "Title of embed."
        },
        {
          "name": "Type",
          "type": "DiscordEmbedType",
          "json": "type",
          "help": "<a href=\"https://discord.com/developers/docs/resources/channel#embed-object-embed-types\">Type of embed</a> (always <c>rich</c> for webhook embeds)."
        },
        {
          "name": "Description",
          "type": "string",
          "json": "description",
          "help": "Description of embed."
        },
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Url of embed."
        },
        {
          "name": "Timestamp",
          "type": "string",
          "json": "timestamp",
          "help": "ISO8601 timestamp of embed."
        },
        {
          "name": "Color",
          "type": "int",
          "json": "color",
          "help": "Color code of the embed."
        },
        {
          "name": "Footer",
          "type": "DiscordEmbedFooter",
          "json": "footer",
          "help": "Footer information."
        },
        {
          "name": "Image",
          "type": "DiscordEmbedImage",
          "json": "image",
          "help": "Image information."
        },
        {
          "name": "Thumbnail",
          "type": "DiscordEmbedThumbnail",
          "json": "thumbnail",
          "help": "Thumbnail information."
        },
        {
          "name": "Author",
          "type": "DiscordEmbedAuthor",
          "json": "author",
          "help": "Author information."
        },
        {
          "name": "Fields",
          "type": "List<DiscordEmbedField>",
          "json": "fields",
          "help": "Fields information."
        }
      ]
    },
    {
      "name": "DiscordEmbedFooter",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Text",
          "type": "string",
          "json": "text",
          "help": "Footer text."
        },
        {
          "name": "IconUrl",
          "type": "string",
          "json": "icon_url",
          "help": "Url of footer icon (only supports http(s) and attachments)."
        }
      ]
    },
    {
      "name": "DiscordEmbedImage",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Source url of image (only supports http(s) and attachments)."
        },
        {
          "name": "Height",
          "type": "int",
          "json": "height",
          "help": "Height of image."
        },
        {
          "name": "Width",
          "type": "int",
          "json": "width",
          "help": "Width of image."
        }
      ]
    },
    {
      "name": "DiscordEmbedThumbnail",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Source url of thumbnail (only supports http(s) and attachments)."
        },
        {
          "name": "Height",
          "type": "int",
          "json": "height",
          "help": "Height of thumbnail."
        },
        {
          "name": "Width",
          "type": "int",
          "json": "width",
          "help": "Width of thumbnail."
        }
      ]
    },
    {
      "name": "DiscordEmbedAuthor",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Name",
          "type": "string",
          "json": "name",
          "help": "Name of author."
        },
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Url of author."
        },
        {
          "name": "IconUrl",
          "type": "string",
          "json": "icon_url",
          "help": "Url of author icon (only supports http(s) and attachments)."
        }
      ]
    },
    {
      "name": "DiscordEmbedField",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Name",
          "type": "string",
          "json": "name",
          "help": "Name of the field."
        },
        {
          "name": "Value",
          "type": "string",
          "json": "value",
          "help": "Value of the field."
        },
        {
          "name": "Inline",
          "type": "bool",
          "json": "inline",
          "help": "Whether or not this field should siplay inline."
        }
      ]
    }
  ],
  "enumerations": [
    {
      "name": "DiscordEmbedType",
      "values": [
        "rich",
        "image",
        "video",
        "gifv",
        "article",
        "link"
      ]
    }
  ]
}
