=== SonnyRR/Fallout/src/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/DotnetPackaging/DotnetPackaging.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/SuperJMN/DotnetPackaging/tree/master/src/DotnetPackaging.Console"
  ],
  "name": "DotnetPackaging",
  "officialUrl": "https://github.com/superjmn/dotnetpackaging",
  "help": "DotnetPackaging is able to package your application into various formats, including Deb and AppImage.",
  "nugetPackageId": "DotnetPackaging.Console",
  "packageExecutable": "DotnetPackaging.Console.dll",
  "tasks": [
    {
      "help": "Creates a Debian package from the specified directory.",
      "postfix": "Deb",
      "definiteArgument": "deb",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the package."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata={value}",
            "help": "The metadata file to include in the package."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output DEB file to create."
          }
        ]
      }
    },
    {
      "help": "Creates an AppImage package.",
      "postfix": "AppImage",
      "definiteArgument": "appimage",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the AppImage."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output AppImage file to create."
          },
          {
            "name": "ApplicationName",
            "type": "string",
            "format": "--application-name={value}",
            "help": "The name of the application for the AppImage."
          },
          {
            "name": "MainCategory",
            "type": "DotnetPackagingMainCategory",
            "format": "--main-category {value}",
            "help": "Main category of the application."
          },
          {
            "name": "AdditionalCategories",
            "type": "List<DotnetPackagingAdditionalCategory>",
            "format": "--additional-categories {value}",
            "help": "Additional categories for the application."
          },
          {
            "name": "Icon",
            "type": "string",
            "format": "--icon {value}",
            "help": "The icon path for the application. When not provided, the tool looks up for an image called <c>AppImage.png</c>."
          },
          {
            "name": "Homepage",
            "type": "string",
            "format": "--homepage {value}",
            "help": "Home page of the application."
          },
          {
            "name": "License",
            "type": "string",
            "format": "--license {value}",
            "help": "License of the application."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "Version of the application."
          },
          {
            "name": "ScreenshotUrls",
            "type": "List<string>",
            "format": "--screenshot-urls {value}",
            "help": "URLs of screenshots of the application."
          },
          {
            "name": "Summary",
            "type": "string",
            "format": "--summary {value}",
            "help": "Short description of the application."
          },
          {
            "name": "AppId",
            "type": "string",
            "format": "--appId {value}",
            "help": "Application ID, usually a reverse DNS name like <c>com.SomeCompany.SomeApplication</c>."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "DotnetPackagingMainCategory",
      "values": [
        "AudioVideo",
        "Audio",
        "Video",
        "Development",
        "Education",
        "Game",
        "Graphics",
        "Network",
        "Office",
        "Settings",
        "Utility"
      ]
    },
    {
      "name": "DotnetPackagingAdditionalCategory",
      "values": [
        "Building",
        "Debugger",
        "IDE",
        "GUIDesigner",
        "Profiling",
        "RevisionControl",
        "Translation",
        "Calendar",
        "ContactManagement",
        "Database",
        "Dictionary",
        "Chart",
        "Email",
        "Finance",
        "FlowChart",
        "PDA",
        "ProjectManagement",
        "Presentation",
        "Spreadsheet",
        "WordProcessor",
        "TwoDGraphics",
        "VectorGraphics",
        "RasterGraphics",
        "ThreeDGraphics",
        "Scanning",
        "OCR",
        "Photography",
        "Publishing",
        "Viewer",
        "TextTools",
        "DesktopSettings",
        "HardwareSettings",
        "Printing",
        "PackageManager",
        "Dialup",
        "InstantMessaging",
        "Chat",
        "IRCClient",
        "FileTransfer",
        "HamRadio",
        "News",
        "P2P",
        "RemoteAccess",
        "Telephony",
        "TelephonyTools",
        "VideoConference",
        "WebBrowser",
        "WebDevelopment",
        "Midi",
        "Mixer",
        "Sequencer",
        "Tuner",
        "TV",
        "AudioVideoEditing",
        "Player",
        "Recorder",
        "DiscBurning",
        "ActionGame",
        "AdventureGame",
        "ArcadeGame",
        "BoardGame",
        "BlocksGame",
        "CardGame",
        "KidsGame",
        "LogicGame",
        "RolePlaying",
        "Simulation",
        "SportsGame",
        "StrategyGame",
        "Art",
        "Construction",
        "Music",
        "Languages",
        "Science",
        "ArtificialIntelligence",
        "Astronomy",
        "Biology",
        "Chemistry",
        "ComputerScience",
        "DataVisualization",
        "Economy",
        "Electricity",
        "Geography",
        "Geology",
        "Geoscience",
        "History",
        "ImageProcessing",
        "Literature",
        "Math",
        "NumericalAnalysis",
        "MedicalSoftware",
        "Physics",
        "Robotics",
        "Sports",
        "ParallelComputing",
        "Amusement",
        "Archiving",
        "Compression",
        "Electronics",
        "Emulator",
        "Engineering",
        "FileTools",
        "FileManager",
        "TerminalEmulator",
        "Filesystem",
        "Monitor",
        "Security",
        "Accessibility",
        "Calculator",
        "Clock",
        "TextEditor",
        "Documentation",
        "Core",
        "KDE",
        "GNOME",
        "GTK",
        "Qt",
        "Motif",
        "Java",
        "ConsoleOnly"
      ]
    }
  ]
}

=== SonnyRR/Fallout/src/Nuke.Common/Tools/NerdbankGitVersioning/NerdbankGitVersioning.json
{
  "$schema": "https://raw.githubusercontent.com/ChrisonSimtian/Fallout/main/src/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md"
  ],
  "name": "NerdbankGitVersioning",
  "officialUrl": "https://github.com/AArnott/Nerdbank.GitVersioning",
  "nugetPackageId": "nbgv",
  "packageExecutable": "nbgv.dll",
  "tasks": [
    {
      "help": "Prepares a project to have version stamps applied using Nerdbank.GitVersioning.",
      "postfix": "Install",
      "definiteArgument": "install",
      "settingsClass": {
        "properties": [
          {
            "name": "Path",
            "type": "string",
            "format": "--path {value}",
            "help": "The path to the directory that should contain the version.json file. The default is the root of the git repo."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "The initial version to set. The default is <c>1.0-beta</c>."
          },
          {
            "name": "Sources",
            "type": "List<string>",
            "format": "--source {value}",
            "separator": " ",
            "help": "The URI(s) of the NuGet package source(s) used to determine the latest stable version of the Nerdbank.GitVersioning package. This setting overrides all of the sources specified in the NuGet.Config files."
          }
        ]
      }
    },
    {
      "help": "Gets the version information for a project.",
      "postfix": "GetVersion",
      "returnType": "NerdbankGitVersioning",
      "definiteArgument": "get-version",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the current directory."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata {value}",
            "help": "Adds an identifier to the build metadata part of a semantic version."
          },
          {
            "name": "Format",
            "type": "NerdbankGitVersioningFormat",
            "format": "--format {value}",
            "help": "The format to write the version information. Allowed values are: <c>text</c>, <c>json</c>. The default is <c>text</c>."
          },
          {
            "name": "Variable",
            "type": "string",
            "format": "--variable {value}",
            "help": "The name of just one version property to print to stdout. When specified, the output is always in raw text. Useful in scripts."
          },
          {
            "name": "CommitIsh",
            "type": "string",
            "format": "-- {value}",
            "help": "The commit/ref to get the version information for. The default is <c>HEAD</c>."
          }
        ]
      }
    },
    {
      "help": "Updates the version stamp that is applied to a project.",
      "postfix": "SetVersion",
      "definiteArgument": "set-version",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "-- {value}",
            "help": "The version to set."
          }
        ]
      }
    },
    {
      "help": "Creates a git tag to mark a version.",
      "postfix": "Tag",
      "definiteArgument": "tag",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "VersionOrRef",
            "type": "string",
            "format": "-- {value}",
            "help": "The <c>a.b.c[.d]</c> version or git ref to be tagged. If not specified, <c>HEAD</c> is used."
          }
        ]
      }
    },
    {
      "help": "Gets the commit(s) that match a given version.",
      "postfix": "GetCommits",
      "definiteArgument": "get-commits",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "Quiet",
            "type": "bool",
            "format": "--quiet",
            "help": "Use minimal output."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "-- {value}",
            "help": "The <c>a.b.c[.d]</c> version to find."
          }
        ]
      }
    },
    {
      "help": "Communicates with the ambient cloud build to set the build number and/or other cloud build variables.",
      "postfix": "Cloud",
      "definiteArgument": "cloud",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory used to calculate the version. The default is the current directory. Ignored if the <c>--version</c> option is specified."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata {value}",
            "help": "Adds an identifier to the build metadata part of a semantic version."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "The string to use for the cloud build number. If not specified, the computed version will be used."
          },
          {
            "name": "CISystem",
            "type": "NerdbankGitVersioningCISystem",
            "format": "--ci-system {value}",
            "help": "Force activation for a particular CI system. If not specified, auto-detection will be used."
          },
          {
            "name": "AllVars",
            "type": "bool",
            "format": "--all-vars",
            "help": "Defines ALL version variables as cloud build variables, with a <c>NBGV_</c> prefix."
          },
          {
            "name": "CommonVars",
            "type": "bool",
            "format": "--common-vars",
            "help": "Defines a few common version variables as cloud build variables, with a <c>Git</c> prefix (e.g. <c>GitBuildVersion</c>, <c>GitBuildVersionSimple</c>, <c>GitAssemblyInformationalVersion</c>)"
          },
          {
            "name": "Variables",
            "type": "Dictionary<string,string>",
            "format": "--define {key}={value}",
            "help": "Additional cloud build variables to define."
          }
        ]
      }
    },
    {
      "help": "Prepares a release by creating a release branch for the current version and adjusting the version on the current branch.",
      "postfix": "PrepareRelease",
      "definiteArgument": "prepare-release",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the current directory."
          },
          {
            "name": "NextVersion",
            "type": "string",
            "format": "--nextVersion {value}",
            "help": " The version to set for the current branch. If omitted, the next version is determined automatically by incrementing the current version."
          },
          {
            "name": "VersionIncrement",
            "type": "string",
            "format": "--versionIncrement {value}",
            "help": "Overrides the 'versionIncrement' setting set in version.json for determining the next version of the current branch."
          },
          {
            "name": "Tag",
            "type": "string",
            "format": "-- {value}",
            "help": "The prerelease tag to apply on the release branch (if any). If not specified, any existing prerelease tag will be removed. The preceding hyphen may be omitted."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "NerdbankGitVersioningFormat",
      "values": [
        "text",
        "json"
      ]
    },
    {
      "name": "NerdbankGitVersioningCISystem",
      "values": [
        "AppVeyor",
        "VisualStudioTeamServices",
        "GitHubActions",
        "TeamCity",
        "AtlassianBamboo",
        "Jenkins",
        "GitLab",
        "Travis"
      ]
    }
  ]
}
